# H2 Database Configuration for Development
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Enable H2 Console
spring.h2.console.enabled=true

# To prevent SQL reserved keyword conflicts with H2, we tell Hibernate to quote all identifiers.
spring.jpa.properties.hibernate.globally_quoted_identifiers=true